# Generated by Django 2.2.6 on 2020-02-11 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('steps', models.DecimalField(decimal_places=0, max_digits=20)),
                ('calories', models.DecimalField(decimal_places=0, max_digits=20)),
                ('deep', models.DecimalField(decimal_places=0, max_digits=20)),
                ('light', models.DecimalField(decimal_places=0, max_digits=20)),
                ('REM', models.DecimalField(decimal_places=0, max_digits=20)),
                ('Wake', models.DecimalField(decimal_places=0, max_digits=20)),
                ('Totaltime', models.DecimalField(decimal_places=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
