# Generated by Django 2.2.6 on 2020-03-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyLiving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='avgRating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fivestarRating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fourstarRating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='onestarRating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='threestarRating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='totalRatings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='twostarRating',
        ),
    ]
