# Generated by Django 2.2.6 on 2020-03-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyLiving', '0003_auto_20200323_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='course',
            field=models.TextField(default=''),
        ),
    ]
