# Generated by Django 2.2.6 on 2020-03-27 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthyLiving', '0004_recipe_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('recipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthyLiving.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
