# Generated by Django 2.2.6 on 2020-03-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyLiving', '0005_recommended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'ordering': ('-Date',)},
        ),
        migrations.RenameField(
            model_name='favourites',
            old_name='date',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='rating',
        ),
    ]
