# Generated by Django 2.2.6 on 2020-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyLiving', '0006_auto_20200330_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='course',
            field=models.TextField(default=''),
        ),
    ]
