# Generated by Django 2.2.6 on 2020-04-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyLiving', '0008_rated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rated',
            options={'ordering': ('rating',)},
        ),
    ]
