# Generated by Django 2.2.6 on 2020-04-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyLiving', '0009_auto_20200423_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rated',
            options={'ordering': ('-rating',)},
        ),
    ]
